owner: vvatelot
repo: upptime

sites:
  - name: Ecoindex.fr website
    url: https://www.ecoindex.fr
  - name: Ecoindex.fr Back For Front
    url: https://bff.ecoindex.fr/health
  - name: Ecoindex.fr Backend API
    url: https://api.ecoindex.fr/health

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitoring Ecoindex.fr"
  introMessage: Retrouvez les disponibilités des composants techniques du site ecoindex.fr
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
